apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: medifollow
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://USER:PASSWORD@cluster0.xxxxx.mongodb.net/"
  MONGODB_DB_NAME: "test"
  JWT_SECRET: "your-jwt-secret"
  GROQ_API_KEY: "your-groq-api-key"
  OPENAI_API_KEY: "your-openai-api-key"
  NODE_ENV: "production"
