apiVersion: v1
kind: Secret
metadata:
  name: medifolllow-secrets
  namespace: default
type: Opaque
stringData:
  MONGODB_URI: "REMPLACE_PAR_TON_URI"
  GMAIL_USER: "REMPLACE_PAR_TON_EMAIL"
  GMAIL_APP_PASSWORD: "REMPLACE_PAR_TON_PASSWORD"
  TWILIO_ACCOUNT_SID: "REMPLACE_PAR_TON_SID"
  TWILIO_AUTH_TOKEN: "REMPLACE_PAR_TON_TOKEN"
  TWILIO_PHONE_NUMBER: "REMPLACE_PAR_TON_NUMERO"
  OPENAI_API_KEY: "REMPLACE_PAR_TA_CLE"